#!/bin/bash

set -uo pipefail

# Configure system locale to en_US.UTF-8
sed -i 's/#\(en_US.UTF-8 UTF-8\)/\1/g' /etc/locale.gen
locale-gen
echo 'LANG=en_US.UTF-8' > /etc/locale.conf

# Fix Pacman.conf
rm -f /etc/pacman.conf
curl https://raw.githubusercontent.com/parchlinux-ports/Parchlinuxarm-images/main/examples/pacman.conf.example >> /etc/pacman.conf

# Enable Sudo
sudo sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers

# Install Desktop and Apps
packages=(
  plasma-bigscreen
  plasma-login-manager
  breeze
  breeze-gtk
  kscreen
  kscreenlocker
  kwayland
  kwin
  kwallet-pam
  libplasma
  plasma-activities
  plasma-activities-stats
  plasma-integration
  plasma-nm
  plasma-pa
  plasma-systemmonitor
  plasma-workspace
  plasma5support
  polkit-kde-agent
  powerdevil
  xdg-desktop-portal-kde
  konsole
  parch-zram
  parch-branding
  noto-fonts
  vazirmatn-fonts
  parch-emoji-ios
  arch-install-scripts
  avahi
  curl
  git
  btop
  man-db
  neovim
  pacman-contrib
  yay-bin
  python
  rsync
  sudo
  tree
  fastfetch
  neofetch-git
  networkmanager
  network-manager-applet
  zsh
  vim
  pipewire
  pipewire-pulse
  bluez
  bluez-utils
  pipewire-alsa
  wireplumber
  rpi-xorg-config
)
pacman -Syu --noconfirm --needed "${packages[@]}"

# Enable services
systemctl enable avahi-daemon NetworkManager
systemctl enable plasmalogin
systemctl enable bluetooth
systemctl enable parch-zram

# Set hostname
echo "ParchPi" > /etc/hostname

# Create parch user and set password
useradd -m -G wheel -s /bin/zsh parch
echo "parch:parch" | chpasswd

# Remove default alarm user
userdel -r alarm || true

# Set root password
echo "root:root" | chpasswd


